# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-04 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('multidb_account', '0003_load_assessments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='team name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=30, verbose_name='team status')),
                ('team_picture', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='team picture')),
                ('tagline', models.TextField(blank=True, max_length=500, verbose_name='team tagline')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='team location')),
                ('season', models.CharField(blank=True, max_length=25, verbose_name='season')),
                ('date_created', models.DateField(default=django.utils.timezone.now, verbose_name='date created')),
                ('athletes', models.ManyToManyField(related_name='team_membership', to='multidb_account.AthleteUser')),
                ('coaches', models.ManyToManyField(related_name='team_membership', to='multidb_account.CoachUser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_ownership', to='multidb_account.CoachUser')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multidb_account.Sport')),
            ],
        ),
    ]
