# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 14:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multidb_account', '0004_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_token_hash', models.CharField(max_length=255, verbose_name='token hash')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('canceled', 'Canceled')], max_length=10, verbose_name='status')),
                ('recipient', models.EmailField(max_length=254, verbose_name='recipient email')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='requester')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multidb_account.Team', verbose_name='team')),
            ],
        ),
    ]
