# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multidb_account', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosenassessment',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multidb_account.Team'),
        ),
    ]
