# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 10:25
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multidb_account', '0005_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecustomuser',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile/', verbose_name='profile picture'),
        ),
    ]
