# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multidb_account', '0006_merge_20170808_1550'),
        ('multidb_account', '0006_alter_user_profile_picture_field'),
    ]

    operations = [
    ]
