# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multidb_account', '0007_merge_20170808_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, verbose_name='team name'),
        ),
    ]
