# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 14:22
from __future__ import unicode_literals

from django.db import migrations
import functools
import imagekit.models.fields
import multidb_account.models


class Migration(migrations.Migration):

    dependencies = [
        ('multidb_account', '0008_auto_20170815_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecustomuser',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(multidb_account.models.get_file_path, *(), **{'path': 'profile/'}), verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(multidb_account.models.get_file_path, *(), **{'path': 'team/'}), verbose_name='profile picture'),
        ),
    ]
