# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 22:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multidb_account', '0012_invite_recipient_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('youtube', 'Youtube'), ('vimeo', 'Vimeo')], max_length=7, verbose_name='video type')),
                ('video_id', models.CharField(max_length=20, verbose_name='video id')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
