# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 14:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0013_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
                ('competition', models.TextField(verbose_name='competition')),
                ('location', models.TextField(blank=True, null=True, verbose_name='location')),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url',
                 models.ImageField(blank=True, max_length=512, null=True, upload_to='', verbose_name='image')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multidb_account.Badge',
                                    verbose_name='badge'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='multidb_account.Team', verbose_name='team'),
        ),
    ]
