# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0015_load_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_name',
            field=models.CharField(default='', max_length=512, verbose_name='video name'),
            preserve_default=False,
        ),
    ]
