# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multidb_account', '0016_video_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='team',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='team'),
        ),
    ]
