# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 18:44
from __future__ import unicode_literals

from django.db import migrations


def remove_gray_badge(apps, schema_editor):
    Badge = apps.get_model('multidb_account', 'Badge')
    Badge.objects.using(schema_editor.connection.alias).filter(image_url__icontains='medal-0').delete()


def reverse_func(apps, schema_editor):
    del apps, schema_editor


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0018_auto_20170831_1400'),
    ]

    operations = [
        migrations.RunPython(remove_gray_badge, reverse_func),
    ]
