# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0020_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletenote',
            name='only_visible_to',
            field=models.ManyToManyField(to='multidb_account.CoachUser'),
        ),
    ]
