# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 20:07
from __future__ import unicode_literals

from django.db import migrations

RETURN_TO_PLAY_TYPES = [
    "Coach",
    "Doctor",
    "Trainer",
    "Chiropractor",
    "Physiotherapy",
    "RMT",
    "Nutritionist",
    "Dietitian"
]


def load_badges(apps, schema_editor):
    ReturnToPlayType = apps.get_model('multidb_account', 'ReturnToPlayType')
    for type_value in RETURN_TO_PLAY_TYPES:
        ReturnToPlayType.objects.using(schema_editor.connection.alias).create(value=type_value)


def reverse_func(apps, schema_editor):
    del apps, schema_editor


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0021_athletenote_only_visible_to'),
    ]

    operations = [
        migrations.RunPython(load_badges, reverse_func),
    ]
