# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 21:03
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0022_auto_20170919_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachnote',
            name='return_to_play_type',
        ),
        migrations.AlterField(
            model_name='athletenote',
            name='return_to_play_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='multidb_account.ReturnToPlayType', verbose_name='return to play type'),
        ),
    ]
