# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 01:33
from __future__ import unicode_literals

from django.db import migrations
import multidb_account.admin.common


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('multidb_account', '0024_remove_achievement_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLogEntry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', multidb_account.admin.common.CustomLogEntryManager()),
            ],
        ),
    ]
