# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 14:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multidb_account', '0025_customlogentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletenote',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='coachnote',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=512, unique=True, validators=[django.core.validators.RegexValidator(regex='((?:https?\\:\\/\\/|www\\.)(?:[-a-z0-9]+\\.)*[-a-z0-9]+.*)')], verbose_name='url'),
        ),
    ]
