# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 14:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multidb_account', '0026_auto_20171016_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='assessmentsubcategory',
            name='parent_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multidb_account.AssessmentSubCategory'),
        ),
        migrations.AlterField(
            model_name='assessmentsubcategory',
            name='parent_top_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multidb_account.AssessmentTopCategory'),
        ),
        migrations.AlterField(
            model_name='assessmenttopcategory',
            name='sport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multidb_account.Sport'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=512, unique=True, validators=[django.core.validators.RegexValidator(regex='(http:\\/\\/www\\.|https:\\/\\/www\\.|http:\\/\\/|https:\\/\\/)?[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\\.[a-z]{2,5}(:[0-9]{1,5})?(\\/.*)?')], verbose_name='url'),
        ),
    ]
