# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0028_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='code')),
                ('discount', models.PositiveSmallIntegerField(verbose_name='discount')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
    ]
