# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multidb_account', '0029_promocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentformat',
            options={'verbose_name': 'Format', 'verbose_name_plural': 'Formats'},
        ),
        migrations.AlterModelOptions(
            name='assessmentrelationshiptype',
            options={'verbose_name': 'Relationship Type', 'verbose_name_plural': 'Relationship Types'},
        ),
        migrations.AlterModelOptions(
            name='assessmentsubcategory',
            options={'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.AlterModelOptions(
            name='assessmenttopcategory',
            options={'verbose_name': 'Top Category', 'verbose_name_plural': 'Top Categories'},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='assessment description'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='relationship_types',
            field=models.ManyToManyField(help_text='One thing that is unique with PSR is defining clear relationships between the assessments and users. There are three types.', to='multidb_account.AssessmentRelationshipType'),
        ),
        migrations.AlterField(
            model_name='assessmentsubcategory',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='assessment category description'),
        ),
        migrations.AlterField(
            model_name='assessmenttopcategory',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='assessment top category description'),
        ),
    ]
