# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 19:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0031_update_assassment_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCenterReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255, verbose_name='organization')),
                ('coach_name', models.CharField(max_length=255, verbose_name='coach name')),
                ('date', models.DateField(verbose_name='date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('details', models.TextField(verbose_name='details')),
                ('name', models.CharField(max_length=255, verbose_name='name', blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Help Center Report',
                'verbose_name_plural': 'Help Center Reports',
            },
        ),
    ]
