# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 14:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0032_help_center_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationUser',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='organisation name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                              related_name='organisation', serialize=False,
                                              to=settings.AUTH_USER_MODEL)),
                ('size', models.IntegerField(blank=True,
                                             choices=[(0, '1-5'), (1, '6-50'), (2, '51-500'), (3, '501-1000'),
                                                      (4, '1001+')], null=True, verbose_name='organisation size')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('sports', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=128, verbose_name='sports'), blank=True, default=list,
                    null=True, size=None)),
            ],
            options={
                'db_table': 'multidb_account_organisation_user',
            },
        ),
        migrations.AddField(
            model_name='basecustomuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(
                message='Phone number must be 9 to 15 digits entered in the format "+999999999" where "+" is optional',
                regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='basecustomuser',
            name='user_type',
            field=models.CharField(
                choices=[('coach', 'Coach'), ('athlete', 'Athlete'), ('organisation', 'organisation')],
                default='athlete', max_length=50, verbose_name='user type'),
        ),
        migrations.AddField(
            model_name='organisationuser',
            name='users',
            field=models.ManyToManyField(related_name='_organisationuser_users_+', to=settings.AUTH_USER_MODEL,
                                         verbose_name='organisation members'),
        ),
    ]
