# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0032_help_center_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteuser',
            name='promocode',
            field=models.CharField(blank=True, max_length=32, verbose_name='promocode'),
        ),
    ]
