# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 13:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0033_organization_and_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='multidb_account.OrganisationUser'),
        ),
        migrations.AlterField(
            model_name='basecustomuser',
            name='user_type',
            field=models.CharField(
                choices=[('coach', 'Coach'), ('athlete', 'Athlete'), ('organisation', 'Organisation')],
                default='athlete', max_length=50, verbose_name='user type'),
        ),
    ]
