# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multidb_account', '0033_add_promocode_to_athleteuser'),
        ('multidb_account', '0034_private_teams'),
    ]

    operations = [
    ]
