# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 17:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0035_merge_20180217_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisationuser',
            name='assessments',
            field=models.ManyToManyField(related_name='organisations', to='multidb_account.Assessment',
                                         verbose_name='private assessments'),
        ),
        migrations.AddField(
            model_name='team',
            name='assessments',
            field=models.ManyToManyField(related_name='teams', to='multidb_account.Assessment',
                                         verbose_name='private assessments'),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='is private'),
        ),
        migrations.AlterField(
            model_name='team',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='multidb_account.OrganisationUser', verbose_name='organisation'),
        ),
    ]
