# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 10:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0037_auto_20180227_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationuser',
            name='users',
            field=models.ManyToManyField(related_name='member_of_organisations', to=settings.AUTH_USER_MODEL,
                                         verbose_name='organisation members'),
        ),
    ]
