# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 22:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0038_alter_organisatinouser_member_of_organisations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationuser',
            name='assessments',
            field=models.ManyToManyField(blank=True, related_name='organisations', to='multidb_account.Assessment',
                                         verbose_name='private assessments'),
        ),
        migrations.AlterField(
            model_name='organisationuser',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='member_of_organisations',
                                         to=settings.AUTH_USER_MODEL, verbose_name='organisation members'),
        ),
    ]
