# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0039_alter_organisationuser_users_assessments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecustomuser',
            name='country',
            field=models.CharField(max_length=7, verbose_name='country iso code'),
        ),
    ]
