# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 18:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0041_rename_organisationuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='users',
            new_name='members',
        ),
        migrations.AddField(
            model_name='organisation',
            name='login_users',
            field=models.ManyToManyField(related_name='organisations', to=settings.AUTH_USER_MODEL),
        ),
    ]
