# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0043_organisation_login_users_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='user',
        ),
        migrations.AddField(
            model_name='organisation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                   verbose_name='ID'),
            preserve_default=False,
        ),
    ]
