# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 12:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0046_fill_team_owner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
        migrations.AlterField(
            model_name='team',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    related_name='team_ownership'),
        ),
        migrations.RenameField(
            model_name='team',
            old_name='owner_user',
            new_name='owner',
        ),
    ]
