# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 10:42
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0047_remove_team_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[
                    django.core.validators.RegexValidator(
                        message='Phone number must be 9 to 15 digits entered in the format "+999999999" '
                                'where "+" is optional',
                        regex='^\\+?1?\\d{9,15}$')])),
                ('support_type', models.CharField(max_length=255, verbose_name='support type')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('details', models.TextField(verbose_name='details')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support',
                                                   to='multidb_account.Organisation', verbose_name='organisation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Organisation Support',
                'verbose_name': 'Organisation Support',
            },
        ),
    ]
