# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0048_organisationsupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecustomuser',
            name='new_dashboard',
            field=models.BooleanField(default=False, verbose_name='new dashboard'),
        ),
    ]
