# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multidb_account', '0050_set_team_coach_athlete_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='private_only',
            field=models.BooleanField(default=False, help_text='Whether to show only private assessments.', verbose_name='private only'),
        ),
    ]
