# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multidb_account', '0051_organisation_private_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athletenote',
            name='doctor',
        ),
    ]
