# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0052_remove_athletenote_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_public_everywhere',
            field=models.BooleanField(
                default=False,
                help_text='If set, treat it as a public one everywhere (teams, organisations, ...).'),
        ),
    ]
