# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multidb_account', '0053_assessment_is_public_everywhere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='assessments',
            new_name='own_assessments',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='private_only',
            new_name='own_assessments_only',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='own_assessments',
            field=models.ManyToManyField(blank=True,
                                         help_text='Those are either <br>a) <b>extra items</b> '
                                                   'shown together with other public items '
                                                   '(when "Own assessments only" disabled) <br>'
                                                   'b) or <b>the only items</b> shown '
                                                   '(when "Own assessments only" enabled).<br>',
                                         related_name='organisations', to='multidb_account.Assessment',
                                         verbose_name='own assessments'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='own_assessments_only',
            field=models.BooleanField(default=False, help_text='Whether to show only own assessments.',
                                      verbose_name='own assessments only'),
        ),
    ]
