# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multidb_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('stripe_id', models.CharField(max_length=255, verbose_name='stripe id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='multidb_account.AthleteUser')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_status', models.CharField(choices=[('up_to_date', 'Up to date'), ('canceled', 'Canceled'), ('grace_period', 'Grace period'), ('locked_out', 'Locked out'), ('no_card', 'No card')], default='no_card', max_length=50, verbose_name='Payment status')),
                ('last_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Last payment date')),
                ('grace_period_start', models.DateTimeField(blank=True, null=True, verbose_name='Grace period start date')),
                ('grace_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Grace period end date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=255, verbose_name='stripe id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(default='', max_length=250, verbose_name='stripe event type ')),
                ('livemode', models.BooleanField(default=False, verbose_name='stripe event livemode ')),
                ('processed', models.BooleanField(default=False, verbose_name='stripe event processed status')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_gateway.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
