# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payment_status',
            field=models.CharField(
                choices=[('up_to_date', 'Up to date'), ('canceled', 'Canceled'), ('grace_period', 'Grace period'),
                         ('locked_out', 'Locked out'), ('no_card', 'No card'), ('not_needed', 'Not needed')],
                default='no_card', max_length=50, verbose_name='Payment status'),
        ),
    ]
